"""v2_14 context-conditioned action: phase classifier head on v2_13 encoder.

The v2_14 stage takes the v2_13 encoder's 32-dim latent and predicts
the task phase label (8 classes: UNKNOWN, MOVE_TO_START, APPROACH,
SEARCH, HOVER_ABOVE_HOLE, INSERT, INSERTED, ABORT) plus a 6-dim
"target joint pose" per phase. The two heads share the latent
input and the same frozen v2_13_v2 encoder.

This is offline training only; it does not need ROS. The script is
registered as a console script so it can be run with
`ros2 run perception_pipeline v2_14_context_conditioned_action -- ...`
for symmetry with the v2_13 tool. It imports nothing from rclpy.

Why a classifier+regressor, not a single action network:
  The 1mm/2mm cartesian precision ceiling with the working JTC means
  real SEARCH/INSERT/ABORT trials are not reachable. The multi-phase
  dataset (v2_13_v2) is generated by synthetic_phase_publisher on a
  frozen arm, so the per-phase joint positions are all the initial
  pose. A direct "context -> joint command" regressor would trivially
  learn to output the initial pose. A phase classifier is the
  meaningful non-trivial task on this dataset: it validates that the
  v2_13 encoder latent is phase-discriminative. A per-phase mean
  target joint regression is added as a sanity check.

Outputs in --output-dir:
    action_classifier.pt    full action head state dict
    action_metadata.json    classifier accuracy, regressor MSE,
                            per-class precision/recall, dataset,
                            timestamp
    confusion_matrix.png    classifier confusion matrix (if matplotlib)
    per_phase_target_pose.json  per-phase mean joint target pose
    data_validation_report.json  input shape, NaN/Inf, class distribution
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Tuple

import numpy as np
import pyarrow.parquet as pq
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset


CONTEXT_DIM = 74
LATENT_DIM = 32
NUM_PHASE_CLASSES = 9
JOINT_DIM = 6
DEFAULT_EPOCHS = 200
DEFAULT_BATCH = 64
DEFAULT_LR = 1e-3
DEFAULT_SEED = 0
HEAD_HIDDEN = 32
HEAD_DROPOUT = 0.10
WEIGHT_DECAY = 1e-4

DEPTH_VALUE_INDICES = (50, 51, 52, 53)
DEPTH_CLIP_VALUE = 5.0


def _load_parquet(path: Path) -> Tuple[np.ndarray, np.ndarray]:
    table = pq.read_table(path)
    df = table.to_pandas()
    if "context_vec" not in df.columns:
        raise RuntimeError(f"parquet is missing 'context_vec' column: {path}")
    X = np.stack([np.array(v, dtype=np.float32) for v in df["context_vec"]])
    if "phase_int" not in df.columns:
        raise RuntimeError(f"parquet is missing 'phase_int' column: {path}")
    phases = df["phase_int"].to_numpy(dtype=np.int64)
    if X.shape[1] != CONTEXT_DIM:
        raise RuntimeError(f"expected context_dim={CONTEXT_DIM}, got {X.shape[1]}")
    return X, phases


def _validate(X: np.ndarray, phases: np.ndarray) -> dict:
    valid_phases = (phases >= 0) & (phases < NUM_PHASE_CLASSES)
    n_dropped = int((~valid_phases).sum())
    return {
        "n_rows": int(X.shape[0]),
        "n_features": int(X.shape[1]),
        "any_nan": bool(np.isnan(X).any()),
        "any_inf": bool(np.isinf(X).any()),
        "phase_unique": sorted(set(phases.tolist())),
        "phase_counts": {
            int(k): int(v)
            for k, v in zip(*np.unique(phases, return_counts=True))
        },
        "n_phase_classes": int(len(np.unique(phases))),
        "n_rows_dropped_unknown_phase": n_dropped,
    }


def _preprocess(X: np.ndarray, mn: np.ndarray, rng: np.ndarray) -> np.ndarray:
    """Apply the v2_13 log1p+minmax transform with a fixed (mn, rng) scaler.

    Empty-camera rows (rgb_sum<1, depth_w==0, depth_h==0) are NOT
    dropped here; the caller does that. This function just does
    feature transform.
    """
    out = X.copy().astype(np.float32)
    for i in DEPTH_VALUE_INDICES:
        out[:, i] = np.clip(out[:, i], 0.0, DEPTH_CLIP_VALUE)
        out[:, i] = np.log1p(out[:, i])
    out = (out - mn) / rng
    return out


def _load_encoder(encoder_path: Path) -> nn.Module:
    ckpt = torch.load(encoder_path, map_location="cpu", weights_only=False)

    class _Enc(nn.Module):
        def __init__(self, input_dim, latent_dim, hidden_dims, dropout):
            super().__init__()
            layers = []
            prev = input_dim
            for h in hidden_dims:
                layers.extend([nn.Linear(prev, h), nn.ReLU(), nn.Dropout(dropout)])
                prev = h
            self.encoder_body = nn.Sequential(*layers)
            self.encoder_head = nn.Linear(prev, latent_dim)

        def encode(self, x):
            return self.encoder_head(self.encoder_body(x))

    enc = _Enc(
        input_dim=ckpt["input_dim"],
        latent_dim=ckpt["latent_dim"],
        hidden_dims=tuple(ckpt["hidden_dims"]),
        dropout=ckpt["dropout"],
    )
    full_state = ckpt["state_dict"]
    encoder_state = {k: v for k, v in full_state.items() if k.startswith("encoder_")}
    enc.load_state_dict(encoder_state)
    enc.eval()
    return enc


class PhaseHead(nn.Module):
    def __init__(self, latent_dim: int = LATENT_DIM, hidden: int = HEAD_HIDDEN,
                 num_classes: int = NUM_PHASE_CLASSES, dropout: float = HEAD_DROPOUT):
        super().__init__()
        self.classifier = nn.Sequential(
            nn.Linear(latent_dim, hidden),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden, num_classes),
        )
        self.regressor = nn.Sequential(
            nn.Linear(latent_dim, hidden),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden, JOINT_DIM),
        )

    def forward(self, z: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        return self.classifier(z), self.regressor(z)


def _compute_per_phase_target(X: np.ndarray, phases: np.ndarray) -> dict:
    out = {}
    for phase_int in sorted(set(phases.tolist())):
        mask = phases == phase_int
        if not mask.any():
            continue
        out[str(int(phase_int))] = X[mask, 60:66].mean(axis=0).tolist()
    return out


def _confusion_matrix(y_true: np.ndarray, y_pred: np.ndarray, n: int) -> np.ndarray:
    cm = np.zeros((n, n), dtype=np.int64)
    for t, p in zip(y_true, y_pred):
        cm[int(t), int(p)] += 1
    return cm


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Train a phase classifier + per-phase target-joint regressor "
            "head on the v2_13 encoder latent. Offline, no ROS."
        )
    )
    parser.add_argument("--input-parquet", required=True)
    parser.add_argument("--encoder-pt", required=True,
                        help="Path to v2_13 encoder.pt (encoder-only checkpoint).")
    parser.add_argument("--scaler-json", required=True,
                        help="Path to v2_13 scaler.json (per-feature min/range).")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--epochs", type=int, default=DEFAULT_EPOCHS)
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH)
    parser.add_argument("--lr", type=float, default=DEFAULT_LR)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    args = parser.parse_args(argv)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"v2_14_context_conditioned_action: output_dir = {output_dir}")

    print(f"v2_14_context_conditioned_action: loading {args.input_parquet}")
    X, phases = _load_parquet(Path(args.input_parquet))
    print(f"v2_14_context_conditioned_action: X.shape = {X.shape} phases.shape = {phases.shape}")

    print("v2_14_context_conditioned_action: validating data")
    report = _validate(X, phases)
    report["input_path"] = str(args.input_parquet)
    with open(output_dir / "data_validation_report.json", "w") as f:
        json.dump(report, f, indent=2)
    print(f"  n_rows={report['n_rows']} n_features={report['n_features']}")
    print(f"  any_nan={report['any_nan']} any_inf={report['any_inf']}")
    print(f"  phase counts: {report['phase_counts']}")
    print(f"  n_phase_classes={report['n_phase_classes']}")

    print("v2_14_context_conditioned_action: dropping empty-camera rows")
    rgb_sum = X[:, :48].sum(axis=1)
    valid = (rgb_sum > 1.0) & (X[:, 48] > 0) & (X[:, 49] > 0)
    n_dropped_empty = int((~valid).sum())
    X = X[valid]
    phases = phases[valid]
    print(f"  dropped {n_dropped_empty} empty-camera rows, kept {X.shape[0]}")

    print(f"v2_14_context_conditioned_action: loading scaler {args.scaler_json}")
    with open(args.scaler_json) as f:
        scaler = json.load(f)
    mn = np.array(scaler["min"], dtype=np.float32)
    mx = np.array(scaler["max"], dtype=np.float32)
    rng = mx - mn
    rng[rng < 1e-8] = 1.0

    print("v2_14_context_conditioned_action: applying v2_13 log1p+minmax transform")
    Xp = _preprocess(X, mn, rng)

    print(f"v2_14_context_conditioned_action: loading v2_13 encoder {args.encoder_pt}")
    encoder = _load_encoder(Path(args.encoder_pt))
    for p in encoder.parameters():
        p.requires_grad = False
    encoder.eval()

    print("v2_14_context_conditioned_action: encoding 74 -> 32 with frozen v2_13 encoder")
    with torch.no_grad():
        Z = encoder.encode(torch.from_numpy(Xp).float()).numpy()
    print(f"  Z.shape = {Z.shape}")

    per_phase_target = _compute_per_phase_target(X, phases)
    y_target = np.zeros((X.shape[0], JOINT_DIM), dtype=np.float32)
    for i, p in enumerate(phases):
        y_target[i] = per_phase_target[str(int(p))]

    rng2 = np.random.default_rng(args.seed)
    idx = rng2.permutation(X.shape[0])
    n_train = int(0.8 * X.shape[0])
    tr_idx, te_idx = idx[:n_train], idx[n_train:]
    Z_train, Z_test = Z[tr_idx], Z[te_idx]
    y_train, y_test = y_target[tr_idx], y_target[te_idx]
    p_train, p_test = phases[tr_idx], phases[te_idx]
    print(f"  train={Z_train.shape[0]} test={Z_test.shape[0]}")

    print(f"v2_14_context_conditioned_action: training {args.epochs} epochs")
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    head = PhaseHead()
    opt = optim.Adam(head.parameters(), lr=args.lr, weight_decay=WEIGHT_DECAY)
    ce = nn.CrossEntropyLoss()
    mse = nn.MSELoss()
    train_ds = TensorDataset(
        torch.from_numpy(Z_train).float(),
        torch.from_numpy(p_train).long(),
        torch.from_numpy(y_train).float(),
    )
    test_ds = TensorDataset(
        torch.from_numpy(Z_test).float(),
        torch.from_numpy(p_test).long(),
        torch.from_numpy(y_test).float(),
    )
    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True)
    test_loader = DataLoader(test_ds, batch_size=args.batch_size, shuffle=False)
    history = []
    for epoch in range(args.epochs):
        head.train()
        cl, rl, n = 0.0, 0.0, 0
        for zb, pb, yb in train_loader:
            opt.zero_grad()
            logits, reg = head(zb)
            lc = ce(logits, pb)
            lr_ = mse(reg, yb)
            loss = lc + lr_
            loss.backward()
            opt.step()
            cl += float(lc.item()) * zb.size(0)
            rl += float(lr_.item()) * zb.size(0)
            n += zb.size(0)
        cl /= max(n, 1)
        rl /= max(n, 1)
        head.eval()
        cl_t, rl_t, n = 0.0, 0.0, 0
        all_pred, all_true = [], []
        with torch.no_grad():
            for zb, pb, yb in test_loader:
                logits, reg = head(zb)
                lc = ce(logits, pb)
                lr_ = mse(reg, yb)
                cl_t += float(lc.item()) * zb.size(0)
                rl_t += float(lr_.item()) * zb.size(0)
                n += zb.size(0)
                all_pred.append(logits.argmax(dim=1).cpu().numpy())
                all_true.append(pb.cpu().numpy())
        cl_t /= max(n, 1)
        rl_t /= max(n, 1)
        y_pred = np.concatenate(all_pred)
        y_true = np.concatenate(all_true)
        acc = float((y_pred == y_true).mean())
        history.append({
            "epoch": epoch,
            "train_ce": cl, "train_mse": rl,
            "test_ce": cl_t, "test_mse": rl_t,
            "test_acc": acc,
        })
        if epoch % max(1, args.epochs // 10) == 0 or epoch == args.epochs - 1:
            print(
                f"  epoch {epoch:4d}  train_ce={cl:.4f} train_mse={rl:.4f}  "
                f"test_ce={cl_t:.4f} test_mse={rl_t:.4f}  test_acc={acc:.3f}"
            )

    final_test_acc = float(history[-1]["test_acc"])
    final_test_ce = float(history[-1]["test_ce"])
    final_test_mse = float(history[-1]["test_mse"])
    print(f"v2_14_context_conditioned_action: final test_acc={final_test_acc:.3f} "
          f"test_ce={final_test_ce:.4f} test_mse={final_test_mse:.6f}")

    print("v2_14_context_conditioned_action: smoke test (reload head, run 1 batch)")
    smoke = PhaseHead()
    smoke.load_state_dict(head.state_dict())
    smoke.eval()
    with torch.no_grad():
        sample = torch.from_numpy(Z_test[:8]).float()
        logits, reg = smoke(sample)
    assert logits.shape == (8, NUM_PHASE_CLASSES), f"logits shape {logits.shape}"
    assert reg.shape == (8, JOINT_DIM), f"reg shape {reg.shape}"
    print(f"  logits shape {tuple(logits.shape)} reg shape {tuple(reg.shape)}")

    ckpt_path = output_dir / "action_classifier.pt"
    torch.save({
        "state_dict": head.state_dict(),
        "input_dim": LATENT_DIM,
        "num_classes": NUM_PHASE_CLASSES,
        "joint_dim": JOINT_DIM,
        "hidden": HEAD_HIDDEN,
        "dropout": HEAD_DROPOUT,
    }, ckpt_path)
    print(f"v2_14_context_conditioned_action: wrote {ckpt_path}")

    cm = _confusion_matrix(p_test, np.array([int(x) for x in y_pred]), NUM_PHASE_CLASSES)
    cm_list = cm.tolist()
    per_class_metrics = {}
    for c in range(NUM_PHASE_CLASSES):
        support = int(cm[c].sum())
        pred_count = int(cm[:, c].sum())
        tp = int(cm[c, c])
        precision = tp / pred_count if pred_count > 0 else 0.0
        recall = tp / support if support > 0 else 0.0
        per_class_metrics[str(c)] = {
            "support": support,
            "predicted_count": pred_count,
            "true_positive": tp,
            "precision": precision,
            "recall": recall,
        }

    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        fig, ax = plt.subplots(figsize=(6, 5))
        im = ax.imshow(cm, cmap="Blues")
        ax.set_xlabel("predicted")
        ax.set_ylabel("true")
        ax.set_title("v2_14 phase classifier confusion matrix")
        for i in range(NUM_PHASE_CLASSES):
            for j in range(NUM_PHASE_CLASSES):
                if cm[i, j] > 0:
                    ax.text(j, i, str(cm[i, j]), ha="center", va="center",
                            color="white" if cm[i, j] > cm.max() / 2 else "black",
                            fontsize=7)
        fig.colorbar(im, ax=ax)
        fig.tight_layout()
        cm_path = output_dir / "confusion_matrix.png"
        fig.savefig(cm_path, dpi=110)
        plt.close(fig)
        print(f"v2_14_context_conditioned_action: wrote {cm_path}")
    except ImportError:
        print("v2_14_context_conditioned_action: matplotlib not available, "
              "skipped confusion_matrix.png")

    metadata = {
        "version": "v2_14",
        "model_type": "phase_classifier_plus_per_phase_joint_regressor",
        "input_dim": LATENT_DIM,
        "num_classes": NUM_PHASE_CLASSES,
        "joint_dim": JOINT_DIM,
        "hidden": HEAD_HIDDEN,
        "dropout": HEAD_DROPOUT,
        "epochs": args.epochs,
        "batch_size": args.batch_size,
        "lr": args.lr,
        "seed": args.seed,
        "weight_decay": WEIGHT_DECAY,
        "final_test_acc": final_test_acc,
        "final_test_ce": final_test_ce,
        "final_test_mse": final_test_mse,
        "n_rows": int(X.shape[0]),
        "n_train": int(Z_train.shape[0]),
        "n_test": int(Z_test.shape[0]),
        "encoder_pt": str(args.encoder_pt),
        "scaler_json": str(args.scaler_json),
        "phase_counts": report["phase_counts"],
        "per_class_metrics": per_class_metrics,
        "per_phase_target_pose": per_phase_target,
        "confusion_matrix": cm_list,
        "history": history,
        "created_utc": int(time.time()),
    }
    metadata_path = output_dir / "action_metadata.json"
    with open(metadata_path, "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"v2_14_context_conditioned_action: wrote {metadata_path}")

    with open(output_dir / "per_phase_target_pose.json", "w") as f:
        json.dump(per_phase_target, f, indent=2)
    print(f"v2_14_context_conditioned_action: wrote per_phase_target_pose.json")

    print("v2_14_context_conditioned_action: done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
