perception_pipeline:
  ros__parameters:
    rgb_topic: /d405/color/image_raw
    depth_topic: /d405/depth/image_rect_raw
    camera_info_topic: /d405/color/camera_info
    output_state_topic: /perception/task_state
